spring:
  application:
    name: GoHommies
  profiles:
    active: dev
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

jwt:
  expiration:
    ms: 36000000
  secret:
    key: '#Q*19zZnKGD4m1K*zhAhg/nYqxFAxpKiHnXMD0h6xYc=BNA4lNva0#uoEkX7uTBaws79UQrdJ&Vqii6QP5ALnkAcwFcbd4ignoqgyzzZYOZS5VdSodBg9Jf!YtsJc#oo'

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
